repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0  # update this revision to your preferred version
    hooks:
      - id: black
        args: ["--line-length", "88"]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # update as needed to match your project requirements
    hooks:
      - id: isort
        args: ["--profile", "black"]
