[mlflow]
experiment_name = "P-CAE"
enable_checkpointing = true
#ckpt_path = "file:///M:/constantinos/data/bio/5-equations/mlruns/1/58a3c85901214e8da5864cce6e0d30d0/artifacts/checkpoints/latest_checkpoint.pth"

[mlflow.server]
host = "localhost"
port = 35382
backend_store_uri = "sqlite:///M:/constantinos/data/bio/5-equations/mlruns/mlflow.db"
default_artifact_root = "file:///M:/constantinos/data/bio/5-equations/mlruns"
tracking_uri = "http://{mlflow.server.host}:{mlflow.server.port}"
terminate_apps_on_port = true

[optuna]

[trainer]
max_epochs = 300
#gradient_clip_val = 5
#fast_dev_run = true

[model]
name = "caes.SkipCAE1d"
latent_size = 5
num_layers = 5
kernel_size = 5
final_channels = 80
final_timesteps = 80

[optimizer]
name = "RAdam"
lr = 1e-3
#weight_decay = 8e-6

[scheduler]
#name = "CosineAnnealingWarmRestarts"
#T_0 = 50
#T_mult = 2
#eta_min = 1e-5
name = "ReduceLROnPlateau"
factor = 0.8
patience = 10
min_lr = 1e-5
#name = "OneCycleLR"
#max_lr = 1e-2
#total_steps = 400

[pruner]

#[[transforms]]
#name = "Log1pSigned"
[[transforms]]
name = "MinMaxScaler"
dim = [0, -1]

[sampler]

[datamodule]
name = "NumpyModule"
test_size = 0.3

[dataloader]
num_workers = 5
batch_size = 128
persistent_workers = true
pin_memory = true

[paths]
dataroot = "M:\\constantinos\\data\\bio\\5-equations"
input = "M:\\constantinos\\data\\bio\\5-equations\\input"
features = "{paths.input}\\p.npy"
output = "{paths.dataroot}\\output"
latent = "{paths.output}\\latent.npy"
figures = "{paths.output}\\figures\\"
predictions = "{paths.output}\\p-predictions.npy"
idx_split = "{paths.input}\\idx_split.json"




